language: python
# if command bellow need to executed in sudo
# add this line.
# sudo: required
python:
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - cd UCrawler; python TravisTest.py;