language: python
# if command bellow need to executed in sudo
# add this line.
# sudo: required
python:
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - cd UCrawler; scrapy crawl NUTC -o unittest/NUTC.json -t json --logfile scrapy.log; python test.py;
  - scrapy crawl NSYSU -o unittest/NSYSU.json -t json --logfile scrapy.log; python test.py;
  - scrapy crawl NTPU -o unittest/NTPU.json -t json --logfile scrapy.log; python test.py;